"""Deterministic stub provider for development and tests. When a JSON schema is supplied it
synthesizes a schema-valid instance; otherwise it echoes a short deterministic note. Its
output is always clearly marked provider='stub' and is never a substitute for a real model."""
from __future__ import annotations

import time

from app.jsonschema_lite import synthesize
from app.providers.base import GenerateRequest, GenerateResult, Provider


class StubProvider(Provider):
    name = "stub"

    def __init__(self, model_version: str = "dev-stub"):
        self.model_version = model_version

    def generate(self, req: GenerateRequest) -> GenerateResult:
        started = time.monotonic()
        note = (
            "[stub provider] No model weights are loaded. This is a deterministic development "
            "placeholder, not a model response."
        )
        json_obj = None
        if req.json_schema is not None:
            json_obj = synthesize(req.json_schema)
            if isinstance(json_obj, dict) and "summary" in json_obj:
                json_obj["summary"] = note
                if "limitations" in json_obj and isinstance(json_obj["limitations"], list):
                    json_obj["limitations"].append(
                        "Generated by the inference stub provider; load a real open-weight model for review."
                    )
        latency = (time.monotonic() - started) * 1000
        return GenerateResult(
            text=note,
            json=json_obj,
            model_version=self.model_version,
            provider=self.name,
            prompt_tokens=len((req.system + req.user).split()),
            completion_tokens=len(note.split()),
            latency_ms=latency,
        )
