"""Deterministic fallback review, used only when the self-hosted model service is
unavailable. Its content is derived entirely from the rule engine and is always labeled
provider="stub" so it is never mistaken for model output."""
from __future__ import annotations

from collections import Counter
from typing import Optional

from app.models.ai_review import AIReview, ReviewItem
from app.rules.base import Evidence, RuleFinding, Severity

STUB_LIMITATION = (
    "Generated by deterministic fallback (provider=stub); model service unavailable. "
    "Content derived solely from the rule engine."
)


def build_stub_review(findings: list[RuleFinding], question: Optional[str] = None) -> AIReview:
    by_sev = Counter(f.severity.value for f in findings)
    ordered = sorted(findings, key=lambda f: (list(Severity).index(f.severity), f.rule_id))

    confirmed = [
        ReviewItem(
            title=f.title,
            detail=f.description,
            severity=f.severity,
            components=list(f.affected_components),
            nets=list(f.affected_nets),
            rule_id=f.rule_id,
            evidence=[e.description for e in f.evidence],
        )
        for f in ordered
    ]
    recommendations = [
        ReviewItem(
            title=f"Fix for {f.rule_id}: {f.title}",
            detail=f.suggested_fix,
            components=list(f.affected_components),
            nets=list(f.affected_nets),
            rule_id=f.rule_id,
        )
        for f in ordered
        if f.suggested_fix
    ]
    evidence = [
        Evidence(kind="rule", reference=f.rule_id, description=f"{f.title} ({f.severity.value})")
        for f in ordered
    ]

    if findings:
        summary = (
            "Deterministic rule engine found "
            + ", ".join(f"{n} {sev}" for sev, n in sorted(by_sev.items()))
            + ". This is a rule-only summary; the specialized model was not available to add "
            "explanation or prioritization."
        )
    else:
        summary = (
            "The deterministic rule engine reported no issues. Absence of rule findings is not a "
            "guarantee of correctness; the specialized model was not available for deeper review."
        )

    return AIReview(
        summary=summary,
        confirmed_findings=confirmed,
        possible_findings=[],
        recommendations=recommendations,
        questions_for_engineer=[],
        evidence=evidence,
        confidence=1.0,  # high only because content is a faithful restatement of rule facts
        limitations=[
            STUB_LIMITATION,
            "No AI explanation, prioritization, or circuit-behavior reasoning is included.",
            "Not a substitute for professional electrical engineering review.",
        ],
    )
